### ISSUE TITLE
show sink fee for mosaics/namespaces ect in explorer

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-explorer#837]
When I go to http://explorer.symbolblockchain.io/transactions/7E3049EBF37DD84C2C52C96A4234281326F3FA434DCFBDA71CF68A194ACB5059

I can see I made a mosaic, but can not see what was the fee I paid to the sink account as part of making this mosaic. 

The same applies to subnamespaces here http://explorer.symbolblockchain.io/namespaces/apostille.io

**Comment by AnthonyLaw** [comment]
It should able to see the fees paid for the namespace.
under namespace detail.

http://explorer.symbolblockchain.io/namespaces/swaps

For some reason `apostille.io` is 0 rental fees, it's because migrated from NIS to Symbol, and generate into genesis block.

You should able to see mosaic fees under the mosaic detail page.
http://explorer.symbolblockchain.io/mosaics/63078E73FBCC2CAC

Should we add the new section to show a receipt for fees as well?

**Comment by jabo38** [comment]
Okay. I can see it. Thanks!
